### ISSUE TITLE
Unusual bug with OpenComputers recipe - crafting ingredient shows up as catalyst!

### ISSUE THREAD

**Issue by MrEldritch** [Towdium/JustEnoughCalculation#32] opened 2017-05-03 21:37 UTC
While trying to find out exactly how much it costs to craft the most basic OpenComputers computer, I ran into a strange issue - the Crafting Calculator was claiming that regular crafting ingredients were catalysts, even when all the recipes involved included no catalyst but a regular crafting bench. 

I posted an album of the relevant screenshots [here](https://imgur.com/a/Zoxh5). You can see that I only have three recipes loaded into the calculator, and each recipe only has a crafting bench in the catalyst slot, but transistors are appearing as a catalyst of the final craft.

I'm using a small, custom 1.10.2 modpack I just threw together; I am using
```
Mods:
  Architect-MC1.10.2-1.0.5.24
  AutoRegLib-1.0-2
  Baubles-1.10.2-1.3.9
  Better With Mods-0.14.22-1.10.2
  BloodMagic-1.10.2-2.1.9-78
  Botania r1.9-341
  Computronics-1.10.2-1.6.3
  foamfix-0.6.2-anarchy
  Guide-API-1.10.2-2.0.3-46
  ImmersiveEngineering-0.10-55
  jei_1.10.2-3.14.7.419
  JustEnoughCalculation-1.10.2-2.6.4
  OpenComputers-MC1.10.2-1.6.2.7
  Quark-r1.1-70
  Railcraft_1.10.2-10.1.1
  redstonepaste-mc1.9.4-1.7.4
```
Which I have not configured at all. The logs do not appear to contain anything that could be relevant to this, either. I'm going to try re-creating these recipes with random vanilla items in the same configuration to see if it's something about the pattern in which the recipes include items from each other.

**Comment by Towdium** [comment] 2017-05-03 22:28
Thanks for report!

Have to admit the catalyst is sometimes weird since I want to make the result dynamic but I haven't find a very reliable algorithm. Although I heven't tried, I think I can reproduce it easily.

It might take some time before it get fixed since my computer is down and I'm stressed on final exams. Will look into it once I got time.

**Comment by Towdium** [comment] 2018-12-09 22:51
Closing this issue since it's too far ago. This problem will not happen in 1.12.

**Closed as completed by Towdium** 2018-12-09 22:51 UTC
Labels: bug
