### ISSUE TITLE
Recipe Output Changes

### ISSUE THREAD

**Issue by dnbrmg** [Towdium/JustEnoughCalculation#25] opened 2016-12-16 00:05 UTC
After updating to version 2.3.1 (the SAG Mill crash fix) I have notice that the output quantities of recipes can in game after using the Calculator item.  For example the vanilla iron bars recipe will return only one Iron Bar instead of 16 or the stick recipe will only provide 1 stick, not 4.  It seems that recipes that would normally return multiples of an item will only return a single instance of that item.  While I can duplicate the error with relative ease I have not been able to figure out the the exact sequence of steps that triggers is outside of a recipe with multiple outputs being involved.  I have a reddit post open with the FTB modded community to see what resources may be availble to chase this down further. 

https://www.reddit.com/r/feedthebeast/comments/5if5l4/odd_receipe_changes_in_game/

**Comment by Towdium** [comment] 2016-12-16 00:16
Honestly speaking, I have no idea with this issue and I cannot reproduce this on my client. As far as I know, there should be nothing related to vanilla recipe registry in the code. Can you confirm this issue disappears after removing JEC?

**Comment by dnbrmg** [comment] 2016-12-17 01:38
I believe I was just able to reproduce the error, or a t leas get closer to a sequence of step to reproduce the error.

Clear out any records stored in the calculator.
Select Iron Bars as the crafting target.
Add the recipe for Iron Bars to the records (I was using the "+" shift click to do so throughout)
Add the Alloy Smelter recipe for Iron Ingots to the records using using the Ender IO powder
Add the Sag Mill recipe for EnderiO iron powder to the records.

Check the iron bars recipe again and this is where the output quantities should have changed.  double check the crafting by crafting the receipt in your favorite crafting table and you should one iron bar out.

I have a theory that I am waiting on the client to  to reload to test.  I will also spend time testing various crafting mechanics without JEC to see what I can find.  I will post those results shortly, in the mean time I have attaches an export of the CurseVoice instance I am testing with.

[Modded 1.10.x (Test)-1.0.zip](https://github.com/Towdium/JustEnoughCalculation/files/658585/Modded.1.10.x.Test.-1.0.zip)

**Comment by dnbrmg** [comment] 2016-12-17 01:39
oops did not mean to close it.  stupid click happy mouse

**Comment by dnbrmg** [comment] 2016-12-17 02:05
After replicating the problem as described above I checked the record of the iron ingots to iron bars recipe in the calculator and the output quantity in the records also got switched to 1 iron bar.  manually adjusting the output quantity to 16 did not affect the crafting recipe, it still only outputs one iron bar until the client is restarted.

**Comment by Towdium** [comment] 2016-12-17 12:42
Thanks a lot for testing, now I can confirm it on the client you gave. This is possibly a mod conflict, it might take me some time to find the reason.

**Comment by Towdium** [comment] 2016-12-17 14:33
I find it. I just messed up some of code in last update. Since JEI passed the original ItemStack in the registry to me and I directly have it changed, the crafting result is changed to an ItemStack that is meant to be a ghost label. That should be fixed in the latest release. If it still happens, do leave more comments.

**Closed as completed** 2016-12-17 14:34 UTC
Labels: fixing
