### ISSUE TITLE
Calculator loses memory, cause unknown.

### ISSUE THREAD

**Issue by Fokson** [Towdium/JustEnoughCalculation#17] opened 2016-09-16 04:37 UTC
Guess who's back!

From time to time, my calculator will lose all of its records and 'groups' on world load (but not 'recent items' memory).  I don't know what is causing it, or how to reproduce it.  I actively tried to get it to forget once I decided to report this, but it seems that when I TRY to get it to lose its memory, it refuses to! =D

Steps taken:
- Save and Quit, reload
- Save and Quit w/ calculator in a chest, reload
- Quitting Minecraft completely, and reloading
- Adding/Removing mods, and reloading.
- Hosting on LAN, quitting, reloading.

I can't think of any other action that would have any relevance to the issue.  I know it's going to be nearly impossible to pin down without any real information, so I apologize.  Just thought I'd document it, however, in case the issues crops up for anyone else.  Perhaps they'll have better insight on the cause and can add to this.

Minecraft 1.10.2
JEC 2.0.1

**Comment by Towdium** [comment] 2016-09-16 15:25
Oops, you know this mod is still in beta version and it has just gone though a totally rewrite, so don't expect it to be too stable, while I'm so sorry to hear that. Honestly speaking, I am faced with more problems that happens randomly, confusing me as well XD.

Actually, the records are stored as user data, independent on the item. I think it might be a multiplayer problem since it has really been a while since last time I test it on MP. I will look into the problem as soon as possible.

Again, thanks a lot for reporting these to me.

**Comment by Towdium** [comment] 2016-09-21 20:51
Just update the latest tests on this issue.

Actually I tested it on multiplayer server and there seems to be nothing lost, so it might not be an MP issue. For the time being, I guess there are two possible reasons, which might be helpful for you to check:
- The login method is changed
- Mods with items recorded is removed, leading to a lost of certain data

Currently I'm not able to reproduce this problem and I will wait for further reports

**Comment by Towdium** [comment] 2017-02-22 11:34
Since there is no progress and no further report on this issue, I would close this issue for the time being. If anyone encounters this issue again, do open another issue.

**Comment by Fokson** [comment] 2017-02-24 00:23
Yeah, sorry.  It still happens and I still don't know why.  The only suggestion I could make to rectify the issue is to have the item itself store the recipe data, and not store it with the character.  I think I've pinned down the trigger to be not when I quit minecraft, but when I quit the launcher and then, after however long, it says 'your token is expired, please log in again'.

**Comment by Towdium** [comment] 2017-02-24 13:34
Oh, that is an important information! 
Can you privide a screenshot of the content in folder `minecraft/saves/%SAVE_NAME%/playerdata`, including the extension. I'm thinking if the UUID of your save is messed up.
By the way, if it is convenient, maybe you can test if boubles have the same issue of losing data.

**Comment by Fokson** [comment] 2017-02-26 22:21
http://puu.sh/uleKT/3c6b3b8f1d.png
7c5 is myself, dea is my roommate who plays on LAN with me.

Though I haven't experienced issues with baubles, he has complained of his baubles disappearing on relog on a number of occasions.

**Comment by Fokson** [comment] 2017-03-06 04:29
Stunning new development.
The calculator seems to have one set of memory when I'm alone in a single player game, and swaps to another set of memory once my roommate joins.  I was playing alone and set up a bunch of recipes, and then the moment he joined those specific recipes were no longer available, but everything that had been there when we were playing last was available again/still.

**Comment by Towdium** [comment] 2017-03-06 15:10
Thanks for you effort!
I think there is enough information to locate the problem but I'm terribly buzy these days. I will get to work once I get time.

**Comment by Towdium** [comment] 2018-12-09 22:58
Closing this issue since it's too far ago. I think this issue should be highly related to Minecraft's different methods when handling single/multi player environment. In 1.12, player data is moved as capability, there should be no such problem.

**Closed as completed by Towdium** 2018-12-09 22:58 UTC
Labels: bug, can't reproduce
