### ISSUE TITLE
SAG mill recipes crash client

### ISSUE THREAD

**Issue by emanb29** [Towdium/JustEnoughCalculation#24] opened 2016-12-13 00:08 UTC
There seems to be a problem wherein trying to automatically add a SAG Mill (from EnderIO) recipe via shift-clicking the "?" icon causes the client to immediately crash. I suspect this is due to the SAG mill having an optional "unused" component (ie either nothing, a dark steel ball, or a piece of flint). The crashlog is reproduced below in full.
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppEngCore (appliedenergistics2-rv4-alpha-5.jar)
  LoadingPlugin (Quark-r1.0-59.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  IC2core (industrialcraft-2-2.6.87-ex110.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.2.334.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 11/28/16 5:18 PM
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at net.minecraft.item.crafting.CraftingManager.func_82787_a(SourceFile:1233)
	at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:95)
	at net.minecraft.inventory.ContainerPlayer.<init>(ContainerPlayer.java:90)
	at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:161)
	at ic2.core.Ic2Player.<init>(Ic2Player.java:18)
	at ic2.core.WorldData.initialize(WorldData.java:74)
	at ic2.core.WorldData.get(WorldData.java:36)
	at ic2.core.WorldData.get(WorldData.java:29)
	at ic2.core.TickHandler.onClientTick(TickHandler.java:122)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_308_TickHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at net.minecraft.item.crafting.CraftingManager.func_82787_a(SourceFile:1233)
	at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:95)
	at net.minecraft.inventory.ContainerPlayer.<init>(ContainerPlayer.java:90)
	at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:161)
	at ic2.core.Ic2Player.<init>(Ic2Player.java:18)
	at ic2.core.WorldData.initialize(WorldData.java:74)
	at ic2.core.WorldData.get(WorldData.java:36)
	at ic2.core.WorldData.get(WorldData.java:29)
	at ic2.core.TickHandler.onClientTick(TickHandler.java:122)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_308_TickHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['emanb29'/5702850, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (160,87,-52), Chunk: (at 0,5,12 in 10,-4; contains blocks 160,0,-64 to 175,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['emanb29'/5702850, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2570177984 bytes (2451 MB) / 4764205056 bytes (4543 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.2.2124 75 mods loaded, 75 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2124.jar) 
	UCHIJA	Forge{12.18.2.2124} [Minecraft Forge] (forge-1.10.2-12.18.2.2124.jar) 
	UCHIJA	appliedenergistics2-core{rv4-alpha-5} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJA	OpenComputers|Core{1.6.0.3-rc.1} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJA	actuallyadditions{1.10.2-r70} [Actually Additions] (ActuallyAdditions-1.10.2-r70.jar) 
	UCHIJA	Baubles{1.3.3} [Baubles] (Baubles-1.10.2-1.3.3.jar) 
	UCHIJA	Botania{r1.9-337} [Botania] (Botania r1.9-337.jar) 
	UCHIJA	AkashicTome{1.0-4} [Akashic Tome] (AkashicTome-1.0-4.jar) 
	UCHIJA	appliedenergistics2{rv4-alpha-5} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-5.jar) 
	UCHIJA	Morphtool{1.0-12} [Morph-o-Tool] (Morph-o-Tool-1.0-12.jar) 
	UCHIJA	Psi{r1.0-41} [Psi] (Psi-r1.0-41.jar) 
	UCHIJA	Quark{r1.0-59} [Quark] (Quark-r1.0-59.jar) 
	UCHIJA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJA	bagginses{2.4.2d} [Bagginses] (Bagginses-1.10.2-3.0.4g.jar) 
	UCHIJA	betterbuilderswands{0.6.5} [Better Builder's Wands] (BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar) 
	UCHIJA	BiomesOPlenty{5.0.0.2091} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2091-universal.jar) 
	UCHIJA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHIJA	mantle{1.10.2-1.1.1.194} [Mantle] (Mantle-1.10.2-1.1.1.jar) 
	UCHIJA	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UCHIJA	immersiveengineering{0.10-48} [Immersive Engineering] (ImmersiveEngineering-0.10-48.jar) 
	UCHIJA	JEI{3.13.2.363} [Just Enough Items] (jei_1.10.2-3.13.2.363.jar) 
	UCHIJA	BloodMagic{1.9.4-2.1.0-66} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-66.jar) 
	UCHIJA	bookshelf{1.4.2.334} [Bookshelf] (Bookshelf-1.10.2-1.4.2.334.jar) 
	UCHIJA	CodeChickenLib{2.4.3.124} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.4.3.124-universal.jar) 
	UCHIJA	brandonscore{2.1.1} [Brandon's Core] (BrandonsCore-1.10.2-2.1.1.61-universal.jar) 
	UCHIJA	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UCHIJA	chisel{MC1.10.2-0.0.7.3} [Chisel] (Chisel-MC1.10.2-0.0.7.3.jar) 
	UCHIJA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJA	chiselsandbits{12.7} [Chisels & Bits] (chiselsandbits-12.7.jar) 
	UCHIJA	CodeChickenCore{2.3.5.91} [CodeChicken Core] (CodeChickenCore-1.10.2-2.3.5.91-universal.jar) 
	UCHIJA	IC2{2.6.87-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.87-ex110.jar) 
	UCHIJA	CompactSolars{5.0.4.328} [Compact Solar Arrays] (CompactSolars-1.10.2-5.0.4.328-universal.jar) 
	UCHIJA	MineTweaker3{3.0.14} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.14.jar) 
	UCHIJA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.14.jar) 
	UCHIJA	CustomMainMenu{2.0.2} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.2.jar) 
	UCHIJA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJA	darkutils{1.1.5.92} [Dark Utilities] (DarkUtilities-1.10.2-1.1.5.96.jar) 
	UCHIJA	forestry{5.2.16.323} [Forestry] (forestry_1.10.2-5.2.16.323.jar) 
	UCHIJA	ElecCore{1.6.328} [ElecCore] (ElecCore-1.10.2-1.6.328.jar) 
	UCHIJA	EnderStorage{2.1.5.84} [EnderStorage] (EnderStorage-1.10.2-2.1.5.84-universal.jar) 
	UCHIJA	OpenComputers{1.6.0.3-rc.1} [OpenComputers] (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar) 
	UCHIJA	deepresonance{1.2.9} [DeepResonance] (deepresonance-1.10-1.2.9.jar) 
	UCHIJA	draconicevolution{2.0.3} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.3.137-universal.jar) 
	UCHIJA	endercore{1.10.2-0.4.1.58-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.58-beta.jar) 
	UCHIJA	EnderIO{1.10.2-3.0.1.126_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.126_beta.jar) 
	UCHIJA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.2.2.jar) 
	UCHIJA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJA	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UCHIJA	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.1.4.jar) 
	UCHIJA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.1.4.jar) 
	UCHIJA	gravestone{1.5.9} [Gravestone] (GraveStone Mod 1.5.9.jar) 
	UCHIJA	inventorysorter{0.10.0+42} [Simple Inventory sorting] (inventorysorter-1.10-0.10.0+42.jar) 
	UCHIJA	ironbackpacks{1.10.2-2.2.13} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.13.jar) 
	UCHIJA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJA	jeibees{0.9.0.4} [JEI Bees] (jeibees-0.9.0.4-mc1.10.2.jar) 
	UCHIJA	journeymap{1.10.2-5.3.0b2} [JourneyMap] (journeymap-1.10.2-5.3.0b2-unlimited.jar) 
	UCHIJA	jeresources{0.5.4.68} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.4.68.jar) 
	UCHIJA	llor{1.1.0-mc[1.9-1.10.2]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.0-mc[1.9-1.10.2].jar) 
	UCHIJA	mercurius{1.0.1} [Mercurius] (Mercurius-1.10.2-1.0.1.jar) 
	UCHIJA	Morpheus{1.10.2-3.1.9} [Morpheus] (Morpheus-1.10.2-3.1.9.jar) 
	UCHIJA	notenoughwands{1.4.0} [Not Enough Wands] (notenoughwands-1.10-1.4.0.jar) 
	UCHIJA	railcraft{10.0.0} [Railcraft] (Railcraft_1.10.2-10.0.0.jar) 
	UCHIJA	rangedpumps{0.3} [Ranged Pumps] (rangedpumps-0.3.jar) 
	UCHIJA	StorageDrawers{1.10.2-3.4.2} [Storage Drawers] (StorageDrawers-1.10.2-3.4.2.jar) 
	UCHIJA	refinedstorage{1.2.4} [Refined Storage] (refinedstorage-1.2.4.jar) 
	UCHIJA	ResourceLoader{1.5.1} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.1.jar) 
	UCHIJA	rftools{5.59} [RFTools] (rftools-1.10-5.59.jar) 
	UCHIJA	rftoolscontrol{1.5.2} [RFTools Control] (rftoolsctrl-1.10-1.5.2.jar) 
	UCHIJA	rftoolsdim{4.45} [RFTools Dimensions] (rftoolsdim-1.10-4.45.jar) 
	UCHIJA	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
	UCHIJA	theoneprobe{1.3.2} [The One Probe] (theoneprobe-1.10-1.3.2.jar) 
	UCHIJA	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCHIJA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.1.213.jar) 
	UCHIJA	wawla{2.3.1.213} [What Are We Looking At] (Wawla-1.10.2-2.3.1.213.jar) 
	Loaded coremods (and transformers): 
AppEngCore (appliedenergistics2-rv4-alpha-5.jar)
  appeng.transformer.asm.ASMIntegration
LoadingPlugin (Quark-r1.0-59.jar)
  vazkii.quark.base.asm.ClassTransformer
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  team.chisel.common.asm.ChiselTransformer
DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  
IC2core (industrialcraft-2-2.6.87-ex110.jar)
  
EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.2.334.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  li.cil.oc.common.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 372.90' Renderer: 'GeForce GTX 970M/PCIe/SSE2'
	AE2 Version: alpha rv4-alpha-5 for Forge 12.18.2.2104
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * An unknown AE2 API is installed (rv4 from appliedenergistics2-rv4-alpha-5.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/F:/Minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/F:/Minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/F:/Minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/F:/Minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/F:/Minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/F:/Minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/F:/Minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/F:/Minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/F:/Minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	AE2 Integration: IC2:ON, RC:OFF, RF:OFF, RFItem:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF
	Launched Version: forge-12.18.2.2124
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970M/PCIe/SSE2 GL version 4.5.0 NVIDIA 372.90, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
```

**Comment by Towdium** [comment] 2016-12-13 00:46
From the crash report, it seems this is caused by the coremod added by IC2. I'm not very familiar with it and it's not open source. So it might take some time before I can figure out the solution, but I will start working on that.

**Comment by Towdium** [comment] 2016-12-13 01:05
Might not be an IC2 issue. I can confirm it even without IC2

**Comment by Towdium** [comment] 2016-12-13 01:49
Should be fixed in latest release. I will close this issue for the time being. If it still have problems, do leave more comments.

**Closed as completed by Towdium** 2016-12-13 01:49 UTC
Labels: bug, fixing
