### ISSUE TITLE
Crash when recipe contains liquids

### ISSUE THREAD

**Issue by davqvist** [Towdium/JustEnoughCalculation#67] opened 2020-05-05 09:47 UTC
https://pastebin.com/KwUfRPQC

In this case it was Pink Slime Ingots (Industrial Foregoing)
Forge 31.1.63
MC 1.15.2
JEC 3.6.1

**Comment by Towdium** [comment] 2020-09-12 03:29
Does it still happen now with latest mod versions? I can't reproduce it.
I'm closing it now, feel free to make more comments.

**Closed as completed by Towdium** 2020-09-12 03:29 UTC
