### ISSUE TITLE
Items texture missing with latest JEI beta

### ISSUE THREAD

**Issue by number5** [Towdium/JustEnoughCalculation#22] opened 2016-11-27 00:57 UTC
See the screenshot below:

<img width="421" alt="screen shot 2016-11-26 at 20 05 58" src="https://cloud.githubusercontent.com/assets/1545/20644799/da634908-b497-11e6-89d1-f0b689effa22.PNG">

Versions:

- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.2.2151
- JustEnoughCalculation: 1.10.2-2.1.4
- JustEnoughItems: 1.10.2-3.13.5.385

**Comment by Towdium** [comment] 2016-11-27 14:16
Thanks for report!

Have tested in the same environment but cannot reproduce.
Can you confirm this issue is caused by updating JEI rather than multiplayer environment, texture pack or other possible things?

Waiting for further information.

**Comment by number5** [comment] 2016-11-27 22:35
Will remove the texturepack tonight and test it again,  though I doubt that's the issue, it works fine till few days ago while I have the texture pack for a while.

Is there any other thing I should look for, e.g. error messages in the logs/etc. ?

**Comment by Towdium** [comment] 2016-11-27 23:41
Actually I'm not sure what's the reason for the time being. If the rendering in other inventories works fine, I guess it is caused by a broken `RenderItem` which I used to tweak the itemstack render. This is from vanilla minecraft, so the reason might be something related to forge or coremods, or some mod conflict. Honestly speaking the `RenderIten` things used to be kind of buggy since there is some reflection, but it has been fine recently.

It would be good if you can test in a clean minecraft instance only with forge and JEI because it works fine on my computer. I have removed nearly all the code related to JEI internal, so it should not be caused by JEI (but who knows).

**Comment by number5** [comment] 2016-11-28 11:13
After trial and error many times, finally found the culprit: CodeChickenLib

I can reproduce the bug just with just 3 mods below: 

```
  CodeChickenLib-1.10.2-2.4.3.145-universal
  jei_1.10.2-3.13.6.387
  JustEnoughCalculation-1.10.2-2.1.4
```

Let me know if you want me to report the bug to CodeChickenLib. 

Cheers

**Comment by Towdium** [comment] 2016-11-28 11:36
Got it！

I can't say this is a bug of ccl, so you don't need to report this issue there. Actually the compatibility with codechicken framework is bugging me for a long time, since it is a coremod and tweaks many of the vanilla behavior. So to ccl, it is just a "feature" rather than "bug". That is the main reason I support JEI rather than NEI.

I will update ccl and check how to fix it. But I cannot promise to fix it very soon since ccl is not a necessary library so I can't use forge's version check.

**Comment by Towdium** [comment] 2016-11-29 18:09
Should be fixed in the latest release, do reopen it if it doesn't work

**Closed as completed** 2016-11-29 18:08 UTC
Labels: fixing
